/**
 * Type definitions for AI-generated test scenarios
 * 
 * This file defines the structure of test scenarios that AI will generate.
 * TypeScript uses these types to ensure the AI output matches what we expect.
 */

/**
 * Type of test scenario
 * - positive: Happy path, normal usage
 * - negative: Error cases, invalid inputs
 * - edge: Boundary conditions, unusual cases
 */
export type ScenarioType = 'positive' | 'negative' | 'edge';

/**
 * Priority level for test scenarios
 * - high: Critical functionality, must test
 * - medium: Important but not critical
 * - low: Nice to have, edge cases
 */
export type Priority = 'high' | 'medium' | 'low';

/**
 * A single test scenario generated by AI
 * 
 * This represents one test case that can be reviewed and potentially
 * implemented as a Playwright test.
 */
export interface TestScenario {
  /** Unique identifier like "SC-001", "SC-002" */
  id: string;
  
  /** Short, descriptive name for the scenario */
  title: string;
  
  /** Detailed description of what we're testing */
  description: string;
  
  /** Type of scenario: positive, negative, or edge */
  type: ScenarioType;
  
  /** Priority level: high, medium, or low */
  priority: Priority;
  
  /** Preconditions that must be met before test execution */
  preconditions: string[];
  
  /** Array of test steps to execute */
  steps: string[];
  
  /** Expected outcome if the test passes */
  expectedResult: string;
}

/**
 * Complete output from AI test scenario generator
 * 
 * This is the structure saved to JSON files in ai-output/
 */
export interface GeneratedScenarios {
  /** The original user story/requirement that was provided */
  requirement: string;
  
  /** Array of test scenarios generated by AI */
  testScenarios: TestScenario[];
  
  /** ISO timestamp when scenarios were generated */
  generatedAt: string;
  
  /** Which AI model was used (e.g., "llama3.2") */
  model: string;
}


