name: Playwright Tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  smoke:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.56.1-jammy
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - run: npm run test:smoke
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-report
          path: playwright-report

      - run: npx allure generate ./allure-results --clean -o ./allure-report
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report-smoke
          path: allure-report

  full:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.56.1-jammy
    env:
      HOME: /root
    needs: smoke
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - run: npm run test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: full-report
          path: playwright-report

      - run: npx allure generate ./allure-results --clean -o ./allure-report
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report
